# Generated by Django 4.1.7 on 2023-03-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='amin', max_length=80),
            preserve_default=False,
        ),
    ]
